### ISSUE TITLE
Incompatible with `tokio v1.40.0`.

### ISSUE THREAD

**Issue by xuxiaocheng0201** [HiRoFa/quickjs_es_runtime#84]
```text
the package `quickjs_runtime` depends on `tokio`, with features: `num_cpus` but `tokio` does not have these features.
```
Version:
```toml
tokio = "^1.40"
quickjs_runtime = "~0.13.4"
```
Silmilar to #75 , but needs to be fixed.

To my knowledge, only these features in [docs](https://docs.rs/tokio/1.40.0/tokio/#feature-flags) of tokio are public.
